[package]
name = "net-ninjas"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = [] }
bevy_asset_loader = "0.24.0"
bevy_screen_diagnostics = "0.8.1"
iyes_progress = "0.15.0"
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }

[patch.crates-io]
bevy_screen_diagnostics = { git = 'https://github.com/GlennMacdonald/bevy_screen_diagnostics.git', rev="51345e28a450c257c852ab22ad6ddb0013dfbb30" }

[features]
default = ["dynamic", "diagnostics"]
diagnostics = []
dynamic = ["bevy/dynamic_linking"]

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

# Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
[profile.wasm-release]
# Default to release profile values.
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"
