name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
      - name: Build
        run: trunk build --release --no-default-features
        working-directory: client/
